In [1]:
#numpy arrays

In [3]:
#They can be both 1d and 2d matrices

In [4]:
my_list=[1,2,3]

In [5]:
import numpy as np

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.eye(4,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.eye(4,5,2,)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.random.rand(4,5)

array([[0.82685998, 0.20777853, 0.76361567, 0.34473529, 0.1043325 ],
       [0.66905174, 0.99654648, 0.53363483, 0.04096963, 0.6184766 ],
       [0.45419526, 0.04526254, 0.50990452, 0.0968534 , 0.37891386],
       [0.41627086, 0.74328518, 0.93745037, 0.0192494 , 0.70720876]])

In [23]:
np.random.randn(2)

array([0.26380822, 0.92155168])

In [24]:
np.random.randint(1,100,10)

array([37, 50, 65, 25, 43,  1, 59, 91, 92, 92])

In [25]:
arr=np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr=np.random.randint(0,50,10)

In [28]:
ranarr

array([30, 20, 24, 26, 38, 42, 33, 23, 43, 10])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

43

In [34]:
ranarr.min()

10

In [35]:
ranarr.argmin()

9

In [37]:
arr.shape

(25,)